### ISSUE TITLE
How to use multiple pages with this approach (firestore_crud_bloc)?

### ISSUE THREAD

**Issue by Er-rchydy** [RobertBrunhage/Youtube-Tutorials#2]
I get this error `bad state stream has already been listened to` when i added `bottomNavigationBar` to `FirestoreCRUDPage`. In all other pages i will use the same stream. but when i tap on bottom navigation to go to a new page i get that error, it tries to listen to the same stream again.
is there a way to prevent that?
thanks for the great work

**Comment by RobertBrunhage** [comment]
Sorry for the late response. 

In that example I am using a normal ´StreamController´ which in default can only be listened to on one place at a time. You can either use a `Broadcast StreamController` or your could use something like `RxDart` `BehaviorSubject`. Both of which will let you listen to a stream on multiple places at the same time!
